// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozgxsgewbxrzrxsnnlzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96Z3hzZ2V3YnhyenJ4c25ubHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTEyNTQsImV4cCI6MjA3MjU2NzI1NH0.AHWse8cTbb54q-FIL1C0ltcu86vzSKOsJYTIgSZBkf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});